/** How the entry fits the catalog (AI apps vs hardware vs retailers). */
export type CatalogKind = "ai" | "software" | "gear" | "hardware";

export type Tool = {
  rank: number;
  name: string;
  category: string;
  helps: string;
  price: string;
  budgetFit: string;
  link: string;
  /** Optional tracked partner URL; falls back to `link` when unset. */
  affiliateLink?: string;
  /** Optional partner logo under `/public` (shown on Partner badges). */
  partnerLogo?: string;
  /** Override when kind is not inferred from category / catalog rank lists. */
  catalogKind?: CatalogKind;
  roles: string[];
  shortDescription?: string;
  howToUse?: string[];
  examplePrompt?: string;
};

export const rolesList = [
  "Director",
  "DOP (Director of Photography)",
  "1st Assistant Director",
  "2nd Assistant Director",
  "Gaffer (Lighting)",
  "Key Grip",
  "Script Supervisor",
  "Location Manager",
  "Production Designer",
  "Costume Designer",
  "Make-up Artist",
  "Producer / Line Producer",
  "Production Coordinator",
  "Lawyer / Clearance",
  "Editor",
  "Sound Designer",
];

export const allTools: Tool[] = [
  {
    rank: 1,
    name: "Runway Gen-4.5",
    category: "Production",
    helps: "Pro filmmaker control surface for text/image/video gen — motion brush, camera paths, and reference consistency (Gen-4.5)",
    price: "from $15/mo (Free tier available)",
    budgetFit: "hollywood",
    link: "runwayml.com",
    roles: ["Editor","DOP (Director of Photography)","Director"],
    shortDescription: "Industry control standard for AI video after Sora — best when you need precise motion and multi-shot craft",
    howToUse: [
      "Step 1: Sign in at runwayml.com",
      "Step 2: Prefer image-to-video from a Midjourney/Flux plate for consistency",
      "Step 3: Use motion brush / camera controls for the exact move",
      "Step 4: Generate alternates; keep one hero take per beat",
      "Step 5: Bring clips into DaVinci or CapCut for assembly",
    ],
    examplePrompt: "Slow dolly-in on a detective at a rainy window, neon bounce, anamorphic bokeh, locked wardrobe from reference still, 10s",
  },
  {
    rank: 2,
    name: "Google Veo 3.1",
    category: "Production",
    helps: "Cinematic text-to-video and image-to-video with native audio, strong prompt adherence, and 4K-oriented output for narrative scenes",
    price: "via Google AI Pro / Ultra (subscription)",
    budgetFit: "both",
    link: "aistudio.google.com",
    roles: ["Director","DOP (Director of Photography)","Editor"],
    shortDescription: "Post-Sora cinematic video model — native audio and photoreal scenes for filmmakers",
    howToUse: [
      "Step 1: Open Google AI Studio (or Gemini apps with Veo access)",
      "Step 2: Choose text-to-video or image-to-video from a locked still",
      "Step 3: Write shot language: lens, move, lighting, and dialogue/SFX if needed",
      "Step 4: Generate, then iterate with the same character/location refs",
      "Step 5: Download and finish in CapCut, DaVinci, or Premiere",
    ],
    examplePrompt: "INT. diner booth, night — medium two-shot, 35mm spherical, soft practical tungsten, rain on window, quiet dialogue, slow push-in, cinematic 2.39:1",
  },
  {
    rank: 3,
    name: "ElevenLabs Voice Cloning",
    category: "Post-Prod",
    helps: "Industry-leading voice cloning, emotional voiceovers, and multi-language dubbing",
    price: "from $5/mo (Free tier available)",
    budgetFit: "both",
    link: "elevenlabs.io",
    roles: ["Sound Designer","Editor","Director"],
    shortDescription: "Best-in-class AI voice cloning and professional dubbing for film",
    howToUse: [
      "Step 1: Go to elevenlabs.io and create an account",
      "Step 2: Upload a short clean audio sample of the voice you want to clone",
      "Step 3: Paste your script or type the dialogue",
      "Step 4: Adjust emotion, pacing, accent, and stability",
      "Step 5: Generate and download the audio file",
    ],
    examplePrompt: "A calm, professional male narrator with slight British accent reading: 'In the quiet moments before dawn, the city held its breath.'",
  },
  {
    rank: 4,
    name: "LTX Studio",
    category: "Pre-Prod",
    helps: "AI-powered storyboarding and production-ready script-to-visual conversion",
    price: "from $10/mo (Free tier available)",
    budgetFit: "indie",
    link: "ltx.studio",
    roles: ["Director","Production Designer","Storyboard Artist"],
    shortDescription: "Fast script-to-storyboard tool with reliable character and location continuity",
    howToUse: [
      "Step 1: Go to ltx.studio and sign up",
      "Step 2: Upload your script or write a scene description",
      "Step 3: Let AI generate storyboards automatically",
      "Step 4: Edit characters, camera angles, and style",
      "Step 5: Export storyboards as images or PDF",
    ],
    examplePrompt: "A tense confrontation in a dimly lit warehouse between a detective and a suspect, rainy night, cinematic lighting",
  },
  {
    rank: 5,
    name: "Kling AI 3.0",
    category: "Production",
    helps: "High-volume cinematic text/image-to-video with strong human motion, multi-shot storytelling, and competitive cost per second",
    price: "Subscription",
    budgetFit: "hollywood",
    link: "kling.ai",
    roles: ["Director","Editor"],
    shortDescription: "Most-used daily AI video workhorse for filmmakers — motion, length, and value after Sora",
    howToUse: [
      "Step 1: Go to kling.ai and create an account",
      "Step 2: Start from an approved still when character lock matters",
      "Step 3: Write camera + action; set duration and aspect",
      "Step 4: Use multi-shot / storyboard modes for scene coverage",
      "Step 5: Download and cut in CapCut or Resolve",
    ],
    examplePrompt: "Image-to-video: woman turns toward camera in a crowded market, handheld follow, fabric and hair physics, warm late-day light, 5s",
  },
  {
    rank: 6,
    name: "Midjourney",
    category: "Pre-Prod",
    helps: "Cinematic concept art, look development, and hero stills that feed Kling, Veo, Runway, and Seedance image-to-video",
    price: "from $10/mo",
    budgetFit: "both",
    link: "midjourney.com",
    roles: ["Production Designer","Director","Storyboard Artist"],
    shortDescription: "Still the look standard — generate plates first, then animate in 2026 video models",
    howToUse: [
      "Step 1: Open Midjourney and set your aspect (e.g. --ar 21:9)",
      "Step 2: Build character and location boards before any motion",
      "Step 3: Upscale hero frames for image-to-video",
      "Step 4: Pair with Flux when you need stricter photoreal prompt fidelity",
      "Step 5: Export refs into your look bible / Pro project",
    ],
    examplePrompt: "Cinematic concept art of a futuristic detective standing on a rainy rooftop, neon lights, blade runner style, highly detailed, dramatic lighting",
  },
  {
    rank: 7,
    name: "Seedance 2.0",
    category: "Production",
    helps: "ByteDance video model with strong physics, multi-shot motion, and native audio — widely used via Dreamina and CapCut after Sora shut down",
    price: "Free tier / CapCut Pro (varies by region)",
    budgetFit: "indie",
    link: "capcut.com",
    roles: ["Director","Editor","Production Coordinator"],
    shortDescription: "High-reach AI video gen after Sora — often used inside CapCut for social and short-form film",
    howToUse: [
      "Step 1: Open CapCut (or Dreamina where Seedance is available in your region)",
      "Step 2: Start from a Midjourney/Flux still when you need character lock",
      "Step 3: Generate with clear camera move + action verbs",
      "Step 4: Use CapCut timeline to cut multi-shot beats",
      "Step 5: Export festival/social versions from the same project",
    ],
    examplePrompt: "Image-to-video: locked character walks through a neon alley, light rain, handheld follow, fabric and reflections hold physics, subtle city ambience",
  },
  {
    rank: 8,
    name: "Flux",
    category: "Pre-Prod",
    helps: "Photoreal image generation with strong prompt fidelity and character consistency for plates, storyboards, and image-to-video starters",
    price: "Free open weights / Pro via API platforms",
    budgetFit: "both",
    link: "blackforestlabs.ai",
    roles: ["Production Designer","Director","Storyboard Artist"],
    shortDescription: "Photoreal stills partner to Midjourney — best for live-action look and consistent characters",
    howToUse: [
      "Step 1: Open Flux via your preferred host (fal, Replicate, or official apps)",
      "Step 2: Lock a character reference before generating scene plates",
      "Step 3: Match aspect ratio to your delivery frame (e.g. 2.39:1)",
      "Step 4: Pick hero stills for Veo / Kling / Seedance / Runway image-to-video",
      "Step 5: Archive refs in your look bible",
    ],
    examplePrompt: "Photoreal production still, INT. kitchen night, practical fridge light, 35mm, shallow DOF, same actress as reference sheet, film grain, no text",
  },
  {
    rank: 9,
    name: "Topaz Video AI",
    category: "Post-Prod",
    helps: "AI video upscaling, denoising, and quality enhancement",
    price: "from $299 one-time",
    budgetFit: "both",
    link: "topazlabs.com",
    roles: ["Editor","DOP (Director of Photography)"],
    shortDescription: "Best tool for upscaling and restoring old or low-quality footage",
    howToUse: [
      "Step 1: Download and install Topaz Video AI",
      "Step 2: Import your video file",
      "Step 3: Choose upscaling, denoising, or stabilization model",
      "Step 4: Adjust settings and preview",
      "Step 5: Export the enhanced video",
    ],
    examplePrompt: "Upscale this 1080p footage to 4K while removing noise and sharpening details",
  },
  {
    rank: 10,
    name: "CapCut",
    category: "Post-Prod",
    helps: "Editor plus generative video (including Seedance where available) for trailers, vertical cutdowns, captions, and fast assembly",
    price: "Free; Pro from ~$8/mo",
    budgetFit: "indie",
    link: "capcut.com",
    roles: ["Editor","Production Coordinator","Director"],
    shortDescription: "Indie finish + gen hub — CapCut is where many filmmakers cut Seedance/Kling clips after Sora",
    howToUse: [
      "Step 1: Import generated clips and production audio",
      "Step 2: Auto-caption dialogue; fix timing",
      "Step 3: Where available, generate Seedance beats inside CapCut",
      "Step 4: Build trailer and social cutdowns from the same timeline",
      "Step 5: Export platform-specific masters",
    ],
    examplePrompt: "45s festival teaser from AI plates + live B-roll, punchy captions, end card with title treatment",
  },
  {
    rank: 11,
    name: "ChatGPT",
    category: "Pre-Prod",
    helps: "Script ideation, dialogue passes, beat sheets, and GPT Image concept frames in one workspace most filmmakers already use",
    price: "Free / Plus / Pro",
    budgetFit: "indie",
    link: "chatgpt.com",
    roles: ["Director","Producer / Line Producer","Script Supervisor"],
    shortDescription: "Default writing + image ideation layer for treatments, rewrites, and quick concept frames",
    howToUse: [
      "Step 1: Paste your logline or rough scene and ask for a formatted screenplay pass",
      "Step 2: Request INT./EXT. scene headings and shot-friendly action lines",
      "Step 3: Generate concept images when you need fast visual options",
      "Step 4: Export dialogue/ADR lists for ElevenLabs",
      "Step 5: Move locked scenes into Filmustage / LTX / your Pro project",
    ],
    examplePrompt: "Rewrite this scene in screenplay format with clear INT./EXT. headings, tighter dialogue, and visual action a DOP can board",
  },
  {
    rank: 12,
    name: "Claude",
    category: "Pre-Prod",
    helps: "Long-context script analysis, structure notes, scene breakdowns, and continuity-aware rewrites for features and series",
    price: "Free / Pro / Team",
    budgetFit: "both",
    link: "claude.ai",
    roles: ["Director","Producer / Line Producer","Script Supervisor"],
    shortDescription: "Best long-form writing partner for structure, breakdowns, and page-one rewrites",
    howToUse: [
      "Step 1: Upload or paste the full script (or act)",
      "Step 2: Ask for beat sheet, character arcs, and weak-scene flags",
      "Step 3: Generate production breakdown lists (cast, locations, props)",
      "Step 4: Tighten dialogue while preserving voice",
      "Step 5: Hand clean scenes to Filmustage or your board tool",
    ],
    examplePrompt: "Analyze this 20-page sample: list scene headings, emotional turn of each scene, and three rewrite notes that improve clarity without changing the genre",
  },
  {
    rank: 13,
    name: "DaVinci Resolve AI",
    category: "Post-Prod",
    helps: "AI-powered color grading, editing, and audio tools in DaVinci Resolve",
    price: "Free / Studio version paid",
    budgetFit: "both",
    link: "blackmagicdesign.com",
    roles: ["Editor","Colorist"],
    shortDescription: "Powerful AI features inside the industry-standard editing software",
    howToUse: [
      "Step 1: Open DaVinci Resolve",
      "Step 2: Import your footage",
      "Step 3: Use Magic Mask, Voice Isolation, or AI color tools",
      "Step 4: Refine with manual adjustments",
      "Step 5: Export the final project",
    ],
    examplePrompt: "Use AI to isolate and enhance dialogue in this noisy location audio",
  },
  {
    rank: 14,
    name: "Filmustage",
    category: "Pre-Prod",
    helps: "AI-powered script breakdown that automatically extracts scenes, characters, locations, props, and generates accurate budgets and shooting schedules",
    price: "from $29/mo",
    budgetFit: "both",
    link: "filmustage.com",
    affiliateLink: "https://filmustage.cello.so/vA2BDdLdP89",
    partnerLogo: "/partners/filmustage.png",
    roles: ["Producer / Line Producer","Director","1st Assistant Director","Script Supervisor"],
    shortDescription: "AI script breakdown and production scheduling",
    howToUse: [
      "Step 1: Go to filmustage.com and sign up",
      "Step 2: Upload your script",
      "Step 3: Let AI perform automatic breakdown",
      "Step 4: Review and edit scenes, characters, and locations",
      "Step 5: Generate budget and shooting schedule",
    ],
    examplePrompt: "Break down this 90-page thriller script and create a detailed shooting schedule",
  },
  {
    rank: 15,
    name: "Pika Labs",
    category: "Production",
    helps: "Fast text-to-video and image-to-video generation for quick clips and VFX previews",
    price: "from $8/mo (Free tier available)",
    budgetFit: "both",
    link: "pika.art",
    roles: ["Director","Editor","Gaffer (Lighting)"],
    shortDescription: "Quick and creative text-to-video tool perfect for on-set previews",
    howToUse: [
      "Step 1: Go to pika.art and create an account",
      "Step 2: Write a text prompt or upload an image",
      "Step 3: Generate multiple variations",
      "Step 4: Extend or remix the best clips",
      "Step 5: Download and import into your editor",
    ],
    examplePrompt: "A slow motion shot of a car exploding with fire and debris flying, cinematic, 4K",
  },
  {
    rank: 16,
    name: "Kira",
    category: "Legal",
    helps: "AI contract analysis and due diligence",
    price: "Subscription",
    budgetFit: "hollywood",
    link: "litera.com/products/kira",
    roles: ["Lawyer / Clearance"],
    shortDescription: "AI contract review and risk analysis for film production",
    howToUse: [
      "Step 1: Go to litera.com and access Kira",
      "Step 2: Upload your contract documents",
      "Step 3: Let AI analyze for risks and clauses",
      "Step 4: Review highlighted issues",
      "Step 5: Generate summary report",
    ],
    examplePrompt: "Analyze this location release form for potential legal risks",
  },
  {
    rank: 17,
    name: "Lexis+ AI",
    category: "Legal",
    helps: "Legal research, summarization, contract review",
    price: "Subscription",
    budgetFit: "hollywood",
    link: "lexisnexis.com",
    roles: ["Lawyer / Clearance"],
    shortDescription: "AI-powered legal research and contract analysis",
    howToUse: [
      "Step 1: Log into Lexis+ AI",
      "Step 2: Ask questions or upload documents",
      "Step 3: Use AI to summarize case law or contracts",
      "Step 4: Review AI-generated insights",
      "Step 5: Export findings",
    ],
    examplePrompt: "Summarize recent case law on film clearance and intellectual property",
  },
  {
    rank: 18,
    name: "Nano Banana Pro",
    category: "Pre-Prod",
    helps: "Google Gemini image path for fast hero frames and storyboard plates (Nano Banana Pro)",
    price: "Free with Google AI Studio",
    budgetFit: "indie",
    link: "gemini.google.com",
    roles: ["Production Designer","Director","Storyboard Artist"],
    shortDescription: "Fast Google-side stills for boards and image-to-video starters",
    howToUse: [
      "Step 1: Go to gemini.google.com",
      "Step 2: Use the image generation feature",
      "Step 3: Write a detailed prompt",
      "Step 4: Generate and refine variations",
      "Step 5: Download images for your storyboard",
    ],
    examplePrompt: "Cinematic wide shot of a lone cowboy riding through a desert at sunset, dramatic lighting, western style",
  },
  {
    rank: 19,
    name: "Ideogram",
    category: "Pre-Prod",
    helps: "Image generation with reliable text-in-image for title cards, posters, signage, and pitch decks",
    price: "Free tier / paid plans",
    budgetFit: "indie",
    link: "ideogram.ai",
    roles: ["Production Designer","Director","Producer / Line Producer"],
    shortDescription: "Poster and title-card stills when readable typography matters",
    howToUse: [
      "Step 1: Create an Ideogram account",
      "Step 2: Prompt with exact title text in quotes",
      "Step 3: Generate poster / title card variants",
      "Step 4: Export for festival packets and social",
      "Step 5: Keep a no-text plate version for video gen if needed",
    ],
    examplePrompt: "Minimal festival poster, dark alley rain, title text \"NIGHT SHIFT\" in clean sans, muted red accent, space for laurels",
  },
  {
    rank: 20,
    name: "Adobe Firefly",
    category: "Pre-Prod",
    helps: "Adobe's generative AI for images, vectors, and in-app fills—available on the web and inside Creative Cloud apps where Firefly features are turned on",
    price: "Subscription",
    budgetFit: "both",
    link: "adobe.com/firefly",
    roles: ["Production Designer","Editor"],
    shortDescription: "Adobe's generative AI layer for concept frames, text-to-image, and Generative Fill-style work that feeds Photoshop, Illustrator, and Premiere—not the Creative Cloud app bundle itself",
    howToUse: [
      "Step 1: Sign in with your Adobe ID and open Firefly on the web or from a supported Creative Cloud app",
      "Step 2: Pick Text to Image or Generative Fill depending on whether you need new frames or edits",
      "Step 3: Align outputs with your aspect ratio, brand palette, and continuity notes from the shot list",
      "Step 4: Export or send assets into Photoshop, Illustrator, or Premiere for finishing",
      "Step 5: Archive approved variants with version names your editorial team can trace",
    ],
    examplePrompt: "Neo-noir alley at night, 35mm lens feel, wet pavement and sodium-vapor glow; generate 4 visual variants, then extend background signage and crowd depth for a Premiere-ready concept comp",
  },
  {
    rank: 21,
    name: "Higgsfield Cinema Studio",
    category: "Production",
    helps: "Applies real film camera profiles (ARRI, RED), lens characteristics, and cinematic lighting to footage or prompts",
    price: "from $9/mo (Free tier available)",
    budgetFit: "both",
    link: "higgsfield.ai",
    roles: ["DOP (Director of Photography)","Director","Gaffer (Lighting)"],
    shortDescription: "Specialty cinema-camera look tool — ARRI/RED profiles and lens simulation (not a general video model)",
    howToUse: [
      "Step 1: Go to higgsfield.ai and create a free account",
      "Step 2: Upload your raw footage or start with a text prompt describing the scene",
      "Step 3: Choose a real film camera profile (ARRI Alexa, RED, etc.) and lens",
      "Step 4: Adjust lighting, depth of field, and add subtle VFX previews",
      "Step 5: Export the enhanced clip and import into your editor",
    ],
    examplePrompt: "A rainy neon street in Tokyo at night, shot on ARRI Alexa Mini LF with anamorphic lenses, moody blue and pink lighting, shallow depth of field, cinematic film grain",
  },
  {
    rank: 22,
    name: "Luma Dream Machine (Ray)",
    category: "Production",
    helps: "Cinematic image-to-video and Dream Machine generation with strong lighting/depth (Ray family)",
    price: "Subscription",
    budgetFit: "both",
    link: "lumalabs.ai/dream-machine",
    roles: ["Director","Editor"],
    shortDescription: "HDR-leaning cinematic motion from stills — lighting and camera feel",
    howToUse: [
      "Step 1: Go to lumalabs.ai/dream-machine and sign up",
      "Step 2: Enter a text prompt or upload an image",
      "Step 3: Generate multiple variations",
      "Step 4: Extend or remix the best results",
      "Step 5: Download the video clips",
    ],
    examplePrompt: "A majestic dragon flying over ancient mountains at sunrise, epic fantasy style, cinematic camera movement",
  },
  {
    rank: 23,
    name: "Luma Ray Relight",
    category: "Post-Prod",
    helps: "AI video relighting tool that realistically changes lighting in existing footage",
    price: "Subscription",
    budgetFit: "both",
    link: "lumalabs.ai/ray",
    roles: ["Gaffer (Lighting)","DOP (Director of Photography)"],
    shortDescription: "AI video relighting for existing footage (Ray relight path)",
    howToUse: [
      "Step 1: Go to lumalabs.ai/ray and sign up",
      "Step 2: Upload your video clip",
      "Step 3: Describe the new lighting you want",
      "Step 4: Adjust intensity and direction",
      "Step 5: Export the relit video",
    ],
    examplePrompt: "Relight this night scene to look like it was shot during golden hour with soft practical lights",
  },
  {
    rank: 24,
    name: "Flawless AI",
    category: "Post-Prod",
    helps: "AI-assisted performance and dialogue editing",
    price: "Subscription",
    budgetFit: "hollywood",
    link: "flawlessai.com",
    roles: ["Editor","Sound Designer"],
    shortDescription: "AI tool for fixing and enhancing actor performances in post",
    howToUse: [
      "Step 1: Go to flawlessai.com and sign up",
      "Step 2: Upload your video clip with dialogue",
      "Step 3: Select the performance you want to improve",
      "Step 4: Let AI generate improved versions",
      "Step 5: Export and replace in your timeline",
    ],
    examplePrompt: "Improve the emotional delivery of this angry confrontation scene while keeping lip sync perfect",
  },
  {
    rank: 25,
    name: "Wonder Studio",
    category: "Production",
    helps: "AI character animation and VFX integration",
    price: "from $40/mo",
    budgetFit: "hollywood",
    link: "wonder.studio",
    roles: ["VFX Artist","Director"],
    shortDescription: "AI-powered character animation for VFX shots",
    howToUse: [
      "Step 1: Go to wonder.studio and create an account",
      "Step 2: Upload your plate footage",
      "Step 3: Add a character rig or use pre-built",
      "Step 4: Let AI animate the character",
      "Step 5: Export and composite in your editor",
    ],
    examplePrompt: "Animate a superhero landing dramatically on a city street at night",
  },
  {
    rank: 26,
    name: "SuperScout.ai",
    category: "Pre-Prod",
    helps: "AI-powered location scouting with photo and availability suggestions for film shoots",
    price: "Subscription",
    budgetFit: "indie",
    link: "superscout.ai",
    roles: ["Location Manager"],
    shortDescription: "AI location scouting with real photos and availability",
    howToUse: [
      "Step 1: Go to superscout.ai and create an account",
      "Step 2: Describe the type of location you need",
      "Step 3: Review AI-suggested locations with photos",
      "Step 4: Check availability and contact info",
      "Step 5: Schedule a visit or book",
    ],
    examplePrompt: "Find abandoned warehouses in Los Angeles suitable for a horror film shoot",
  },
  {
    rank: 27,
    name: "Massif Network",
    category: "Pre-Prod",
    helps: "AI + VR hybrid location scouting platform for virtual pre-vis and real-world scouting",
    price: "Subscription",
    budgetFit: "both",
    link: "massif.network",
    roles: ["Location Manager","Production Designer"],
    shortDescription: "VR + AI hybrid location scouting and pre-vis",
    howToUse: [
      "Step 1: Go to massif.network and sign up",
      "Step 2: Describe your location needs",
      "Step 3: Explore virtual tours of suggested locations",
      "Step 4: Save favorites and share with team",
      "Step 5: Contact real locations for scouting",
    ],
    examplePrompt: "Find a Victorian mansion for a period drama with good natural light",
  },
  {
    rank: 28,
    name: "Style2D AI",
    category: "Pre-Prod",
    helps: "AI character and costume design",
    price: "Subscription",
    budgetFit: "both",
    link: "style3d.ai",
    roles: ["Costume Designer","Production Designer"],
    shortDescription: "AI tool for generating character and costume designs",
    howToUse: [
      "Step 1: Go to style2d.ai and create an account",
      "Step 2: Describe the character, period, and style",
      "Step 3: Generate multiple design variations",
      "Step 4: Refine colors, details, and accessories",
      "Step 5: Export high-resolution images for production",
    ],
    examplePrompt: "Create a detailed cyberpunk hacker costume for a female lead character, dark tones with neon accents",
  },
  {
    rank: 29,
    name: "Browzwear",
    category: "Pre-Prod",
    helps: "AI 3D garment and costume visualization",
    price: "Enterprise",
    budgetFit: "hollywood",
    link: "browzwear.com",
    roles: ["Costume Designer"],
    shortDescription: "Professional 3D garment design and visualization software",
    howToUse: [
      "Step 1: Open Browzwear software",
      "Step 2: Create or import garment patterns",
      "Step 3: Apply fabrics and textures",
      "Step 4: Use AI to generate realistic 3D previews",
      "Step 5: Export for production and team review",
    ],
    examplePrompt: "Visualize a Victorian-era ball gown in silk with intricate lace details on a digital model",
  },
  {
    rank: 30,
    name: "Google Vids",
    category: "Post-Prod",
    helps: "AI-powered video editor for professional videos",
    price: "Subscription",
    budgetFit: "both",
    link: "workspace.google.com/products/vids",
    roles: ["Editor","Production Coordinator"],
    shortDescription: "Simple AI video editor integrated with Google Workspace",
    howToUse: [
      "Step 1: Open Google Workspace and access Vids",
      "Step 2: Upload footage or start a new project",
      "Step 3: Use AI to suggest edits and transitions",
      "Step 4: Add voiceover or text with AI help",
      "Step 5: Export the final video",
    ],
    examplePrompt: "Turn this 45-minute meeting footage into a 3-minute summary video",
  },
  {
    rank: 31,
    name: "Light Depth (Luminar Neo)",
    category: "Post-Prod",
    helps: "AI relighting and dramatic lighting enhancement for still frames and photo-based VFX",
    price: "Subscription",
    budgetFit: "both",
    link: "skylum.com",
    roles: ["Gaffer (Lighting)","DOP (Director of Photography)"],
    shortDescription: "Powerful AI relighting for photos and VFX plates",
    howToUse: [
      "Step 1: Open Luminar Neo",
      "Step 2: Import your image or plate",
      "Step 3: Use Relight AI tool",
      "Step 4: Adjust light direction and intensity",
      "Step 5: Export the relit image",
    ],
    examplePrompt: "Relight this dark interior scene with dramatic window light coming from the left",
  },
  {
    rank: 32,
    name: "Suno AI",
    category: "Post-Prod",
    helps: "AI music and song generation",
    price: "Subscription",
    budgetFit: "both",
    link: "suno.com",
    roles: ["Sound Designer"],
    shortDescription: "Fast AI music and full song generation with lyrics",
    howToUse: [
      "Step 1: Go to suno.com and create an account",
      "Step 2: Describe the style and mood of the music",
      "Step 3: Add lyrics if desired",
      "Step 4: Generate several versions",
      "Step 5: Download the audio tracks",
    ],
    examplePrompt: "Epic orchestral trailer music with intense strings and powerful drums, cinematic, dark tone",
  },
  {
    rank: 33,
    name: "Udio",
    category: "Post-Prod",
    helps: "AI music generation with high quality",
    price: "Subscription",
    budgetFit: "both",
    link: "udio.com",
    roles: ["Sound Designer"],
    shortDescription: "High-quality AI music generator with excellent vocal synthesis",
    howToUse: [
      "Step 1: Go to udio.com and sign up",
      "Step 2: Describe the genre and mood",
      "Step 3: Add custom lyrics if needed",
      "Step 4: Generate and compare versions",
      "Step 5: Download the best track",
    ],
    examplePrompt: "Emotional piano ballad with male vocals about loss and hope, cinematic film score style",
  },
  {
    rank: 34,
    name: "AIVA",
    category: "Post-Prod",
    helps: "AI music composition for film scores",
    price: "Subscription",
    budgetFit: "hollywood",
    link: "aiva.ai",
    roles: ["Sound Designer","Composer"],
    shortDescription: "AI composer specialized in cinematic film scores",
    howToUse: [
      "Step 1: Go to aiva.ai and create an account",
      "Step 2: Choose film score genre and mood",
      "Step 3: Set duration and instrumentation",
      "Step 4: Generate and refine the composition",
      "Step 5: Export as audio or MIDI",
    ],
    examplePrompt: "Dark, suspenseful orchestral score for a thriller chase scene, building tension",
  },
  {
    rank: 35,
    name: "Boords",
    category: "Pre-Prod",
    helps: "AI-assisted storyboarding tool",
    price: "Subscription",
    budgetFit: "indie",
    link: "boords.com",
    roles: ["Director","Storyboard Artist"],
    shortDescription: "Simple and fast AI-assisted storyboarding platform",
    howToUse: [
      "Step 1: Go to boords.com and sign up",
      "Step 2: Create a new storyboard project",
      "Step 3: Use AI to generate frames from script",
      "Step 4: Edit drawings, add notes, and camera angles",
      "Step 5: Export as PDF or share with team",
    ],
    examplePrompt: "Create storyboard frames for a dialogue-heavy bar scene at night",
  },
  {
    rank: 36,
    name: "Katalist",
    category: "Pre-Prod",
    helps: "AI script breakdown and scheduling",
    price: "Subscription",
    budgetFit: "both",
    link: "katalist.ai",
    roles: ["Producer / Line Producer","1st Assistant Director"],
    shortDescription: "AI script breakdown and production scheduling assistant",
    howToUse: [
      "Step 1: Go to katalist.ai and create an account",
      "Step 2: Upload your script",
      "Step 3: Let AI perform automatic breakdown",
      "Step 4: Review and edit scenes, characters, and locations",
      "Step 5: Generate budget and shooting schedule",
    ],
    examplePrompt: "Break down this 95-page thriller script and create a detailed shooting schedule",
  },
  {
    rank: 37,
    name: "Studiobinder",
    category: "Pre-Prod",
    helps: "Production management and script breakdown tools",
    price: "Subscription",
    budgetFit: "both",
    link: "studiobinder.com",
    roles: ["Producer / Line Producer","Director","Script Supervisor","1st Assistant Director"],
    shortDescription: "Comprehensive production management and script breakdown platform",
    howToUse: [
      "Step 1: Go to studiobinder.com and sign up",
      "Step 2: Create a new project and upload script",
      "Step 3: Use AI breakdown tools",
      "Step 4: Build shot lists, call sheets, and schedules",
      "Step 5: Collaborate with team and export documents",
    ],
    examplePrompt: "Create a full production bible for a 10-day short film shoot",
  },
  {
    rank: 38,
    name: "Celx AI",
    category: "Post-Prod",
    helps: "AI video editing and enhancement",
    price: "Subscription",
    budgetFit: "both",
    link: "celx.ai",
    roles: ["Editor"],
    shortDescription: "AI-assisted video editing and enhancement tool",
    howToUse: [
      "Step 1: Go to celx.ai and create an account",
      "Step 2: Upload your footage",
      "Step 3: Let AI suggest cuts and enhancements",
      "Step 4: Review and fine-tune the edit",
      "Step 5: Export the final video",
    ],
    examplePrompt: "Automatically edit this 30-minute raw interview into a tight 5-minute highlight reel",
  },
  {
    rank: 39,
    name: "Feiyu SCORP 2",
    category: "Production",
    helps: "Motorized camera gimbal for stabilized handheld shots; companion app adds cinematic presets and subject tracking—physical rig first, smart features second",
    price: "Hardware + app",
    budgetFit: "both",
    link: "www.feiyu-tech.com",
    catalogKind: "hardware" as const,
    roles: ["Gaffer (Lighting)","DOP (Director of Photography)","Key Grip"],
    shortDescription: "Handheld stabilization rig for production—optional app-based cinematic and tracking assists",
    howToUse: [
      "Step 1: Set up the Feiyu SCORP 2 gimbal",
      "Step 2: Connect to the Feiyu ON app",
      "Step 3: Enable AI tracking or cinematic modes",
      "Step 4: Record smooth stabilized footage",
      "Step 5: Transfer footage to your editing computer",
    ],
    examplePrompt: "Use AI tracking to follow a running actor smoothly through a crowded market",
  },
  {
    rank: 40,
    name: "Descript",
    category: "Post-Prod",
    helps: "Transcript-first video and podcast editing with Overdub, Studio Sound, filler-word removal, and multitrack timelines for fast assembly cuts",
    price: "from $12/mo (Free tier available)",
    budgetFit: "both",
    link: "descript.com",
    affiliateLink: "https://get.descript.com/p4dqbwe4hu34",
    roles: ["Editor","Sound Designer","Production Coordinator"],
    shortDescription: "Edit video by editing text — ideal for rough cuts, ADR notes, and dialogue-heavy scenes",
    howToUse: [
      "Step 1: Import footage or record directly in Descript",
      "Step 2: Let Descript transcribe; cut and rearrange by deleting or moving text",
      "Step 3: Use Studio Sound to clean noisy location audio where safe",
      "Step 4: Add titles, captions, and simple graphics in the timeline",
      "Step 5: Export sequence or publish to review links for producers",
    ],
    examplePrompt: "Rough-cut this 18-minute interview down to 6 tight minutes, remove ums and long pauses, and flag lines that need ADR",
  },
  {
    rank: 41,
    name: "Leonardo.ai",
    category: "Pre-Prod",
    helps: "Image generation with motion, character reference pipelines, and style-consistent boards for pitch decks and look development",
    price: "from $10/mo (Free tier available)",
    budgetFit: "both",
    link: "leonardo.ai",
    roles: ["Production Designer","Director","DOP (Director of Photography)"],
    shortDescription: "Cinematic stills and motion previews for mood boards when you need control beyond a single generalist model",
    howToUse: [
      "Step 1: Create a project and set aspect ratio to match your delivery frame",
      "Step 2: Upload reference stills for character or location consistency",
      "Step 3: Iterate prompts with negative prompts to reduce artifact hands and faces",
      "Step 4: Use motion or short clip modes for pre-vis beats where offered",
      "Step 5: Export PNG sequences or boards for the art department PDF",
    ],
    examplePrompt: "Neo-noir alley at blue hour, rain on cobblestones, lone detective in trench coat, 2.39:1, film grain, no text",
  },
  {
    rank: 42,
    name: "HeyGen",
    category: "Post-Prod",
    helps: "AI avatars, lip-sync translation, and talking-head video for pickups, explainers, and multilingual marketing without a reshoot",
    price: "from $24/mo (Free trial)",
    budgetFit: "both",
    link: "heygen.com",
    roles: ["Producer / Line Producer","Editor","Production Coordinator"],
    shortDescription: "Turn scripts into presenter-led video and localized dubs when cast cannot return to set",
    howToUse: [
      "Step 1: Choose an avatar or upload talent-approved likeness per clearance rules",
      "Step 2: Paste script lines and set pacing; preview lip sync",
      "Step 3: Translate voice and captions for festival or streaming territories",
      "Step 4: Brand with lower-thirds and logo safe areas",
      "Step 5: Export MP4 for EPK or distributor deliverables checklist",
    ],
    examplePrompt: "30-second director statement for a festival site, warm tone, English and Spanish voice tracks",
  },
  {
    rank: 43,
    name: "Synthesia",
    category: "Pre-Prod",
    helps: "Studio-style AI presenters and templated scenes for pitch videos, investor updates, and crew onboarding with brand-safe avatars",
    price: "from $22/mo (Trial)",
    budgetFit: "hollywood",
    link: "synthesia.io",
    roles: ["Producer / Line Producer","Production Coordinator","Lawyer / Clearance"],
    shortDescription: "Polished talking-head explainers when you need legal-approved avatars instead of unpaid cast pickups",
    howToUse: [
      "Step 1: Pick a template layout matching your aspect ratio",
      "Step 2: Write scene copy; split into short beats for natural cadence",
      "Step 3: Swap avatars and backgrounds to match brand guidelines",
      "Step 4: Add on-screen bullet points for budget or schedule walkthroughs",
      "Step 5: Export with subtitles burned in for review meetings",
    ],
    examplePrompt: "Two-minute investor deck walkthrough of a $1.2M indie slate, neutral office background, SRT captions",
  },
  {
    rank: 44,
    name: "OpusClip",
    category: "Post-Prod",
    helps: "Long-form to short-form AI that finds hooks, reframes faces, and adds captions for viral-style clips from interviews and panels",
    price: "from $9/mo (Free tier)",
    budgetFit: "indie",
    link: "opus.pro",
    affiliateLink: "https://www.opus.pro/?via=9f898c",
    roles: ["Editor","Production Coordinator","Producer / Line Producer"],
    shortDescription: "Repurpose premiere Q&As and podcasts into vertical clips without manual scrubbing every beat",
    howToUse: [
      "Step 1: Upload a long interview or panel recording",
      "Step 2: Let Opus suggest highlight moments; reorder by story priority",
      "Step 3: Tune hook text and caption style for readability on phones",
      "Step 4: Crop to 9:16 with smart face tracking for talking heads",
      "Step 5: Batch export for a week of festival social posts",
    ],
    examplePrompt: "From a 42-minute filmmaker Q&A, create 8 clips under 45s each with strong openers and burned-in captions",
  },
  {
    rank: 45,
    name: "InVideo AI",
    category: "Post-Prod",
    helps: "Script-to-video workflows with stock-aware scenes, AI voiceover, and template libraries for promos and crowdfunding videos",
    price: "from $15/mo (Free tier)",
    budgetFit: "both",
    link: "invideo.io",
    affiliateLink: "https://invideo.sjv.io/c/7233581/883681/12258",
    roles: ["Producer / Line Producer","Editor","Director"],
    shortDescription: "Ship a credible Kickstarter or festival trailer fast when you lack an in-house motion designer",
    howToUse: [
      "Step 1: Start from a trailer or explainer template close to your genre",
      "Step 2: Paste script; map beats to scenes and swap stock where needed",
      "Step 3: Generate AI voiceover or upload guide track for timing",
      "Step 4: Adjust color blocks and typography to match one-sheet branding",
      "Step 5: Export 1080p master plus vertical variants",
    ],
    examplePrompt: "90-second crowdfunding video for a sci-fi proof-of-concept, urgent tone, three reward tiers on screen",
  },
  {
    rank: 46,
    name: "PixVerse",
    category: "Production",
    helps: "Text and image-to-video with stylized motion control for fantasy, anime-influenced, and stylized B-roll that would be costly practically",
    price: "from $8/mo (Free tier)",
    budgetFit: "both",
    link: "pixverse.ai",
    roles: ["Director","Editor","DOP (Director of Photography)"],
    shortDescription: "Quick stylized motion plates for pitch reels and VFX previs when photorealism is not the goal",
    howToUse: [
      "Step 1: Sign in and pick duration and aspect ratio for your plate",
      "Step 2: Write a motion-heavy prompt with camera verbs (dolly, pan, orbit)",
      "Step 3: Seed from a keyframe still if you have concept art",
      "Step 4: Generate variants; pick the least artifact-heavy pass",
      "Step 5: Download and comp over temp audio in your NLE",
    ],
    examplePrompt: "Orbiting shot around a floating island city at sunset, painterly style, slow parallax, no logos",
  },
  {
    rank: 47,
    name: "Hedra",
    category: "Production",
    helps: "Character-centric video from images and audio with expressive faces — useful for stylized dialogue plates and creature mouth movement tests",
    price: "from $10/mo (Free tier)",
    budgetFit: "both",
    link: "hedra.com",
    roles: ["Director","Editor","Sound Designer"],
    shortDescription: "Animate a still or simple rig toward lip-sync when you need a cheap blocking pass before VFX",
    howToUse: [
      "Step 1: Upload a clean frontal or three-quarter reference image",
      "Step 2: Add or generate audio aligned to line reads",
      "Step 3: Preview facial motion; reduce intensity if uncanny",
      "Step 4: Iterate on lighting cues in the prompt if supported",
      "Step 5: Export clip for editorial temp or pitch-only use (check likeness rights)",
    ],
    examplePrompt: "Portrait of an elderly inventor in his workshop speaks a 12-second monologue, warm practicals, subtle head motion",
  },
  {
    rank: 48,
    name: "Mubert",
    category: "Post-Prod",
    helps: "Generative and loopable royalty-aware music beds for edits, mood tests, and temp scores before composer spotting",
    price: "from $14/mo (Free tier)",
    budgetFit: "indie",
    link: "mubert.com",
    affiliateLink: "https://mubert.com/render/pricing?via=eva-riinitze",
    roles: ["Sound Designer","Editor","Director"],
    shortDescription: "Infinite-ish stems tuned by mood and BPM so editors can cut without fighting a fixed master",
    howToUse: [
      "Step 1: Choose genre, energy, and length to match scene duration",
      "Step 2: Generate several seeds; favorite the closest emotional fit",
      "Step 3: Export WAV or stems if the plan allows for light mixing",
      "Step 4: Drop under picture; note temp vs licensed final in EDL comments",
      "Step 5: Replace with composer final before distribution",
    ],
    examplePrompt: "Tense 2-minute underscore for a midnight stakeout, low sub pulse, no drums, 90 BPM, minor key",
  },
  {
    rank: 49,
    name: "Beatoven.ai",
    category: "Post-Prod",
    helps: "AI scoring with section-based dynamics for YouTube-ready beds, documentary cues, and mood shifts without manual MIDI programming",
    price: "from $10/mo (Free tier)",
    budgetFit: "indie",
    link: "beatoven.ai",
    roles: ["Sound Designer","Editor","Director"],
    shortDescription: "Region-based intensity changes for doc scenes that breathe between interview and vérité",
    howToUse: [
      "Step 1: Set project length to match timeline gap",
      "Step 2: Pick genre pack closest to your sonic palette",
      "Step 3: Add emotion ramps at scene boundaries",
      "Step 4: Preview against picture in your DAW or NLE",
      "Step 5: Export licensed WAV and archive the license receipt",
    ],
    examplePrompt: "Documentary cue: hopeful strings building over 90s into a restrained climax when the subject wins the appeal",
  },
  {
    rank: 50,
    name: "Soundraw",
    category: "Post-Prod",
    helps: "Mood, genre, and instrument sliders for custom-length royalty-friendly tracks suited to recurring series or tight indie schedules",
    price: "from $17/mo",
    budgetFit: "both",
    link: "soundraw.io",
    affiliateLink: "https://soundraw.io/?ref=ildargvr",
    roles: ["Sound Designer","Editor","Producer / Line Producer"],
    shortDescription: "Dial in instrumentation when you need repeatable sonic branding across episodes or campaign cuts",
    howToUse: [
      "Step 1: Select length to match cut duration exactly",
      "Step 2: Lock key instruments you want present or absent",
      "Step 3: Generate alternatives; star the closest to reference track",
      "Step 4: Adjust energy curve for act breaks",
      "Step 5: Export full mix and keep project file for recuts",
    ],
    examplePrompt: "Dark synthwave bed for a 2.5-minute chase, no vocals, rising percussion in final 30 seconds",
  },
  {
    rank: 51,
    name: "Magnific AI",
    category: "Post-Prod",
    helps: "Generative upscaling and detail enhancement for stills and plates — useful for poster blowups and soft VFX still enlargement when resolution is short",
    price: "from $39/mo",
    budgetFit: "hollywood",
    link: "magnific.ai",
    roles: ["Editor","Production Designer","DOP (Director of Photography)"],
    shortDescription: "Creative upscale with texture control for key art and texture-critical restoration previews",
    howToUse: [
      "Step 1: Upload highest-quality still or extracted frame",
      "Step 2: Choose target resolution and creativity slider conservatively for faces",
      "Step 3: Run preview tiles before full render to catch hallucinations",
      "Step 4: Compare against Topaz-style conservative pass if you need fidelity",
      "Step 5: Export TIFF for print or PNG for motion plate import",
    ],
    examplePrompt: "Upscale a 2K anamorphic still to print-ready 24x36 poster, preserve skin texture, minimal hallucinated jewelry",
  },
  {
    rank: 52,
    name: "Scriptation",
    category: "Production",
    helps: "Digital script-lining, facing pages, and note transfer across PDF revisions — built for script supervisors marking coverage, props, and continuity on iPad and Mac",
    price: "from $13/mo (Free trial)",
    budgetFit: "both",
    link: "scriptation.com",
    roles: ["Script Supervisor","Editor","Director"],
    shortDescription: "Industry-standard markup and revision sync so continuity notes survive new script drops without retyping",
    howToUse: [
      "Step 1: Import the production PDF or Final Draft export",
      "Step 2: Use lining layers for coverage, eyelines, and circle takes",
      "Step 3: Photo-link wardrobe or set continuity into script pages",
      "Step 4: When a new draft arrives, migrate annotations with Scriptation’s transfer tools",
      "Step 5: Export facing pages or reports for editorial and production office",
    ],
    examplePrompt: "Mark Scene 42 for 2:1 coverage, flag a wardrobe watch on the hero’s watch band, and prep editor-facing notes for the director’s cut",
  },
  {
    rank: 53,
    name: "Studiovity",
    category: "Pre-Prod",
    helps: "Cloud pre-production suite with AI-assisted breakdowns, stripboards, shot lists, and call-sheet prep tied into scheduling exports",
    price: "from $19/mo (Free tier)",
    budgetFit: "both",
    link: "studiovity.com",
    roles: ["Script Supervisor","1st Assistant Director","Producer / Line Producer"],
    shortDescription: "Keeps breakdown tags, stripboard order, and department-facing reports aligned before the first production meeting",
    howToUse: [
      "Step 1: Upload script and run AI breakdown for cast, props, wardrobe, and locations",
      "Step 2: Review and correct tags with the script supervisor before locking",
      "Step 3: Generate stripboard drafts from scene order and company moves",
      "Step 4: Export elements lists for departments and attach to shared drive",
      "Step 5: Push schedule revisions when pages are cut or scenes combine",
    ],
    examplePrompt: "Rebuild the stripboard after combining Night INT. warehouse scenes 12–14 and regenerate department element lists",
  },
  {
    rank: 54,
    name: "Rivet AI",
    category: "Pre-Prod",
    helps: "AI script breakdowns, schedule drafts, and budget estimates from screenplay text — aimed at line producers validating scope before locking Movie Magic",
    price: "from $49/mo (Trial)",
    budgetFit: "hollywood",
    link: "rivetai.com",
    roles: ["Script Supervisor","Producer / Line Producer","1st Assistant Director"],
    shortDescription: "Stress-test page counts and company moves early so script sup notes and AD stripboards do not fight the budget reality",
    howToUse: [
      "Step 1: Import script and generate automated element extraction",
      "Step 2: Compare AI day-out-of-days against the script supervisor’s continuity flags",
      "Step 3: Adjust turnaround assumptions for child or animal rules",
      "Step 4: Export schedule assumptions to share with UPM and HoD meetings",
      "Step 5: Re-run when major rewrite drops to re-baseline shoot length",
    ],
    examplePrompt: "Estimate shoot days for a 108-page ensemble drama with dual units and highlight where split days strain continuity coverage",
  },
  {
    rank: 55,
    name: "SetHero",
    category: "Production",
    helps: "Digital call sheets, crew confirmations, and distro lists with weather, hospitals, and nearest parking — reduces morning confusion for grip trucks and splinter units",
    price: "from $15/mo (Free trial)",
    budgetFit: "both",
    link: "sethero.com",
    roles: ["Key Grip","1st Assistant Director","Production Coordinator"],
    shortDescription: "Key grips see rigging call times, basecamp maps, and safety notes on mobile before the truck pack is finalized",
    howToUse: [
      "Step 1: Build call sheet from schedule import or template",
      "Step 2: Add parking pins, crane base zones, and tech-scout photos for grip parking",
      "Step 3: Push distro to department heads and confirm read receipts",
      "Step 4: Update weather and hospital block for remote locations",
      "Step 5: Archive day’s PDF for insurance and union time paperwork",
    ],
    examplePrompt: "Crane day on Stage 4: add 6am rigging crew call, map C-stand staging lane, and attach lensing PDF for the gaffer team",
  },
  {
    rank: 56,
    name: "Cheqroom",
    category: "Production",
    helps: "Equipment reservation, checkout QR codes, and maintenance logs for dollies, cranes, and grip packages across prep and shoot weeks",
    price: "from $29/mo (Free tier)",
    budgetFit: "both",
    link: "cheqroom.com",
    roles: ["Key Grip","Production Coordinator","Producer / Line Producer"],
    shortDescription: "Tracks which grip package left the prep dock and when it must return so splinter units do not double-book the Fisher dolly",
    howToUse: [
      "Step 1: Catalog cranes, dollies, and consumable kits with photos and serials",
      "Step 2: Reserve gear to shoot dates and assign responsible best boy or key grip",
      "Step 3: Scan check-out at load-out; scan check-in after wrap",
      "Step 4: Flag damaged hardware with photo evidence for rental house claims",
      "Step 5: Export month-end utilization for rental vs owned ROI",
    ],
    examplePrompt: "Reserve 12x12 solids and a PeeWee for Unit B next Tuesday and alert if the package conflicts with the commercial prep hold",
  },
  {
    rank: 57,
    name: "Envato Elements",
    category: "Post-Prod",
    helps: "Subscription library of stock video, music, SFX, graphics, and templates for fast rough cuts, pitch decks, and social deliverables",
    price: "from $16.50/mo",
    budgetFit: "both",
    link: "elements.envato.com",
    roles: ["Editor","Sound Designer","Director"],
    shortDescription: "One subscription for stock assets so editorial can move while waiting on final shoots and composer handoff",
    howToUse: [
      "Step 1: Build a project collection by scene type and mood",
      "Step 2: Pull temporary music and SFX for rough cut pacing",
      "Step 3: Use title and transition templates for preview exports",
      "Step 4: Replace placeholders with licensed final selections before delivery",
      "Step 5: Archive license receipts with project paperwork",
    ],
    examplePrompt: "Find tense newsroom ambience, subtle glitch transition pack, and minimalist lower thirds for a political thriller teaser",
  },
  {
    rank: 58,
    name: "Wondershare Filmora",
    category: "Post-Prod",
    helps: "Full editing suite with timeline tools plus AI-assisted captions, filler cleanup, and templates for promo and trailer cuts—not only a generic utility app",
    price: "from $49.99/yr",
    budgetFit: "indie",
    link: "filmora.wondershare.com",
    affiliateLink: "https://www.jdoqocy.com/click-7947848-13530874?sid=35mmmai-home",
    roles: ["Editor","Director","Producer / Line Producer"],
    shortDescription: "AI-assisted editing suite for publishable promo cuts and trailers when you want more than a bare-bones editor",
    howToUse: [
      "Step 1: Start with a vertical, square, or widescreen preset",
      "Step 2: Drop interview or BTS footage into a simple timeline",
      "Step 3: Auto-generate captions and clean filler words",
      "Step 4: Apply consistent color and title templates for brand continuity",
      "Step 5: Export platform-specific versions for socials and ads",
    ],
    examplePrompt: "Cut a 30-second festival teaser from BTS clips, add burned-in captions, and export 9:16 plus 16:9 versions",
  },
  {
    rank: 59,
    name: "Kapwing",
    category: "Post-Prod",
    helps: "Browser-based editor for quick captioning, resizing, and collaborative review on trailer snippets and announcement posts",
    price: "from $16/mo (Free tier)",
    budgetFit: "both",
    link: "kapwing.com",
    roles: ["Editor","Producer / Line Producer","Director"],
    shortDescription: "Great for rapid social repackaging without moving every change through the full finishing timeline",
    howToUse: [
      "Step 1: Upload a cut or paste a hosted clip link",
      "Step 2: Auto-caption and fix names, film terms, and timing",
      "Step 3: Duplicate timeline into 16:9, 1:1, and 9:16 layouts",
      "Step 4: Share review link for producer notes",
      "Step 5: Export social-ready masters with safe margins",
    ],
    examplePrompt: "Turn a 90-second director interview into a 20-second vertical quote clip with bold captions and logo end card",
  },
  {
    rank: 60,
    name: "VEED",
    category: "Post-Prod",
    helps: "Online editing and subtitle workflow for creator-style marketing videos, explainers, and quick launch announcements",
    price: "from $18/mo (Free tier)",
    budgetFit: "both",
    link: "veed.io",
    roles: ["Editor","Producer / Line Producer","Director"],
    shortDescription: "Fast subtitle and format conversion tool when marketing needs same-day variants",
    howToUse: [
      "Step 1: Upload cut and choose target channel preset",
      "Step 2: Generate subtitles and correct film-specific vocabulary",
      "Step 3: Add branded intro/outro and CTA card",
      "Step 4: Resize to vertical and square without re-editing from scratch",
      "Step 5: Export compressed versions for each platform",
    ],
    examplePrompt: "Create subtitled 15-second and 30-second launch clips from the same trailer and add website CTA at end",
  },
  {
    rank: 61,
    name: "Artlist",
    category: "Post-Prod",
    helps: "Licensed music and SFX catalog for trailer temping, branded content, and documentary underscore with clear usage terms",
    price: "from $9.99/mo",
    budgetFit: "both",
    link: "artlist.io",
    roles: ["Sound Designer","Editor","Director"],
    shortDescription: "Reliable licensing path when you need strong temp tracks that can stay in final cut",
    howToUse: [
      "Step 1: Filter by mood, BPM, and instrument for scene intent",
      "Step 2: Test multiple cues against dialogue-heavy and montage sections",
      "Step 3: Download stems where available for cleaner mix control",
      "Step 4: Track selected cue IDs in your music report",
      "Step 5: Confirm final license scope before release",
    ],
    examplePrompt: "Find a slow-build cinematic cue for a reveal scene with strings and sub pulse that peaks at 1:20",
  },
  {
    rank: 62,
    name: "Pictory",
    category: "Post-Prod",
    helps: "Text and long-form-to-short-form video repackaging for behind-the-scenes explainers and social snippets",
    price: "from $25/mo",
    budgetFit: "indie",
    link: "pictory.ai",
    roles: ["Editor","Producer / Line Producer","Director"],
    shortDescription: "Quickly converts interviews or podcasts into short promo clips when time is limited",
    howToUse: [
      "Step 1: Import script, article, or long-form video",
      "Step 2: Let AI suggest key moments and visual pairings",
      "Step 3: Swap weak stock picks with stronger branded visuals",
      "Step 4: Add subtitles and trim for 15–45 second social formats",
      "Step 5: Export multiple captioned variants for testing",
    ],
    examplePrompt: "Turn a 12-minute podcast segment about indie budgeting into three 30-second subtitled clips",
  },
  {
    rank: 63,
    name: "Canva",
    category: "Pre-Prod",
    helps: "Fast design tool for pitch decks, lookbooks, one-sheets, and social key art when dedicated design bandwidth is limited",
    price: "from $14.99/mo (Free tier)",
    budgetFit: "both",
    link: "canva.com",
    roles: ["Producer / Line Producer","Director","Production Designer"],
    shortDescription: "Useful for professional-looking presentations and promo graphics without waiting on a separate design pipeline",
    howToUse: [
      "Step 1: Start from a film pitch deck or poster template",
      "Step 2: Add stills, palette swatches, and typography references",
      "Step 3: Build matching social cards for casting and launch posts",
      "Step 4: Export PDF deck plus PNG assets for distribution",
      "Step 5: Share editable link for collaborator updates",
    ],
    examplePrompt: "Create a 10-slide pitch deck visual style with moody noir palette, location references, and cast mood board page",
  },
  {
    rank: 64,
    name: "Shutterstock",
    category: "Post-Prod",
    helps: "Stock footage, stills, and editorial assets for placeholders, transitions, and missing inserts during edit crunch",
    price: "from $29/mo",
    budgetFit: "both",
    link: "shutterstock.com",
    roles: ["Editor","Producer / Line Producer","Director"],
    shortDescription: "Large library for patching coverage gaps or creating polished temporary cuts during reshoot uncertainty",
    howToUse: [
      "Step 1: Search by shot type, location, and movement",
      "Step 2: Pull watermarked comps to validate pacing in edit",
      "Step 3: License finals only after creative lock",
      "Step 4: Keep clip IDs and receipts tied to project folders",
      "Step 5: Replace temporary assets before final conform if needed",
    ],
    examplePrompt: "Find aerial dusk city transitions and neutral office b-roll to bridge scene jumps in a corporate thriller cut",
  },
  {
    rank: 65,
    name: "Motion Array",
    category: "Post-Prod",
    helps: "Template and asset marketplace for Premiere/After Effects style graphics, transitions, and sound design packs",
    price: "from $24.99/mo",
    budgetFit: "both",
    link: "motionarray.com",
    roles: ["Editor","Sound Designer","Director"],
    shortDescription: "Accelerates finishing by using proven template kits for titles, transitions, and social cutdowns",
    howToUse: [
      "Step 1: Pick template packs matching genre and tone",
      "Step 2: Import project files into your NLE or motion app",
      "Step 3: Replace placeholders with film branding and shots",
      "Step 4: Sync transition timing with score beats",
      "Step 5: Export reusable presets for future episodes or campaigns",
    ],
    examplePrompt: "Build a gritty opener package with kinetic titles, lens dirt overlays, and whoosh SFX for a crime mini-series promo",
  },
  {
    rank: 66,
    name: "B&H Photo Video",
    category: "Gear",
    helps: "Major retailer for cinema cameras, lenses, lighting, audio, grip, computers, and editing/post hardware — pair with the gear planner when pricing purchases vs rentals",
    price: "Cart pricing (varies)",
    budgetFit: "both",
    link: "www.bhphotovideo.com",
    roles: ["Producer / Line Producer","DOP (Director of Photography)","Key Grip","Editor"],
    shortDescription: "Primary retailer path when your budget shifts from rental quotes to buying bodies, glass, lights, or edit workstations",
    howToUse: [
      "Step 1: Build your kit list in 35mmAI, then search B&H for each line item’s buy price",
      "Step 2: Compare manufacturer bundles vs à la carte glass and media",
      "Step 3: Add tripods, bags, and spare batteries while cart value is still in one shipment",
      "Step 4: Park tax-exempt or reseller paperwork if your production company qualifies",
      "Step 5: Save invoices next to rental paperwork for insurance and resale records",
    ],
    examplePrompt: "Price a Sony FX6 package with two budget primes, Nanlite key light, and CFexpress cards for a 4-week doc shoot vs renting locally",
  },
  {
    rank: 67,
    name: "Adorama",
    category: "Gear",
    helps: "Photo, video, pro audio, and computing retailer — compare bundles, kits, and open-box against your gear-planner buy lines",
    price: "Cart pricing (varies)",
    budgetFit: "both",
    link: "www.adorama.com",
    roles: ["Producer / Line Producer","DOP (Director of Photography)","Editor"],
    shortDescription: "Cross-check prices and bundles when your gear planner flags buy scenarios for cameras, lenses, or studio gear",
    howToUse: [
      "Step 1: Export your shortlist from prep and search Adorama for matching SKUs",
      "Step 2: Compare open-box or kit discounts against MAP bundles",
      "Step 3: Stack education or loyalty offers if your account qualifies",
      "Step 4: Align delivery dates with prep week before camera tests",
      "Step 5: File receipts with the line producer for cost-report actuals",
    ],
    examplePrompt: "Find a mid-tier mirrorless cinema kit plus on-camera mic and SD media under a $6k purchase cap for a student feature",
  },
  {
    rank: 68,
    name: "CyberLink PowerDirector",
    category: "Post-Prod",
    helps: "Windows-focused NLE with AI-assisted editing, motion titles, and effects — built for fast turnaround and vertical/social exports on PC",
    price: "from ~$69.99/yr (PowerDirector 365; regional offers vary)",
    budgetFit: "indie",
    link: "www.cyberlink.com/products/powerdirector",
    roles: ["Editor","Director","Producer / Line Producer"],
    shortDescription: "AI-powered timeline editing when your post pipeline is Windows-heavy and you want templates plus fast social exports",
    howToUse: [
      "Step 1: Set project to your delivery aspect ratios (16:9, 9:16, 1:1)",
      "Step 2: Use AI-assisted tools for rough assembly and reframing where available",
      "Step 3: Layer titles and motion graphics from built-in libraries",
      "Step 4: Export platform presets for festival promo and ads",
      "Step 5: Archive project packages for pickup editors",
    ],
    examplePrompt: "Cut a 45-second Windows-only promo from mixed H.264 dailies with bold captions for Meta ads",
  },
  {
    rank: 69,
    name: "Adobe Creative Cloud",
    category: "Post-Prod",
    helps: "The Adobe software subscription: Premiere Pro, After Effects, Audition, Photoshop, Lightroom, and related apps—traditional creative tools for edit, motion, sound, and imaging (distinct from Adobe Firefly's generative AI services)",
    price: "from $22.99/mo (single app); All Apps from ~$59.99/mo (plans vary by region)",
    budgetFit: "both",
    link: "www.adobe.com/creativecloud",
    catalogKind: "software" as const,
    roles: ["Editor","Sound Designer","Director","Producer / Line Producer"],
    shortDescription: "Adobe's Creative Cloud subscription for Premiere, After Effects, Audition, Photoshop, and the rest of the pro app suite—classic post-production software, not an AI-only generator",
    howToUse: [
      "Step 1: Choose a plan covering Premiere, After Effects, and Audition as needed",
      "Step 2: Standardize project settings to your delivery spec (frame rate, color space)",
      "Step 3: Use Productions or shared projects for editor + AE artist split",
      "Step 4: Round-trip Audition for noisy location repair where applicable",
      "Step 5: Export mastering codecs per distributor checklist",
    ],
    examplePrompt: "Set up a Premiere Productions workspace for a 90-minute feature with separate reels for editor and color",
  },
  {
    rank: 70,
    name: "Movavi Video Suite",
    category: "Post-Prod",
    helps: "Prosumer editing, screen recording, and media conversion in one ecosystem — suited to fast promo cuts and lightweight finishing when budget is tight",
    price: "from ~$29.95/mo subscription (annual/perpetual offers vary)",
    budgetFit: "indie",
    link: "www.movavi.com/video-suite",
    roles: ["Editor","Producer / Line Producer","Director"],
    shortDescription: "Low-friction editing and conversion stack for teasers, screen captures, and quick masters when schedule beats polish",
    howToUse: [
      "Step 1: Import mixed phone and camera codecs into one timeline",
      "Step 2: Trim interview and B-roll for festival announcement cuts",
      "Step 3: Capture screen recordings for crowdfunding or tutorial extras",
      "Step 4: Export compressed review files for producer notes",
      "Step 5: Keep license keys in the production vault for reinstalls",
    ],
    examplePrompt: "Assemble a 2-minute Kickstarter pitch from phone B-roll plus voiceover recorded in the same app chain",
  },
  {
    rank: 71,
    name: "VideoProc",
    category: "Post-Prod",
    helps: "GPU-accelerated video processing: convert, compress, record, and quick-edit — ideal for proxies, screeners, and delivery variants from a laptop",
    price: "from ~$25.95 one-time license (promotional pricing varies)",
    budgetFit: "indie",
    link: "www.videoproc.com",
    roles: ["Editor","Production Coordinator","Producer / Line Producer"],
    shortDescription: "Transcode, compress, and tweak clips when dailies codecs or delivery specs do not match your NLE timeline",
    howToUse: [
      "Step 1: Batch transcode HEVC or LOG clips to edit-friendly proxies",
      "Step 2: Trim and merge clips for investor-only screeners",
      "Step 3: Compress masters for festival upload caps",
      "Step 4: Rip supplementary codecs for archive drives",
      "Step 5: Document settings next to DCP or platform specs",
    ],
    examplePrompt: "Convert a folder of 4K H.265 interview files to ProRes proxy for an offline Premiere reel",
  },
  {
    rank: 72,
    name: "Google Flow",
    category: "Production",
    helps: "AI filmmaking studio built around Veo 3.1, Imagen, and Gemini — generate cinematic clips with native audio, reference ingredients, and assemble scenes in one project workspace",
    price: "Free 50 credits/day; Google AI Pro from ~$19.99/mo (1,000 credits); Ultra from ~$249.99/mo",
    budgetFit: "both",
    link: "labs.google/flow",
    roles: ["Director","DOP (Director of Photography)","Editor"],
    shortDescription: "Google's Veo-first creative studio for cinematic pre-vis and generative sequences with continuity controls",
    howToUse: [
      "Step 1: Open labs.google/flow with a Google AI Pro or Ultra account",
      "Step 2: Create a project and set aspect ratio to match delivery",
      "Step 3: Build character and location ingredients with Imagen reference stills",
      "Step 4: Generate Veo clips with explicit camera and lighting prompts",
      "Step 5: Extend scenes and export clips for your NLE timeline",
    ],
    examplePrompt: "2.39:1 night interior — detective at rain-streaked window, slow push-in, practical lamp key, native room tone and dialogue",
  },
  {
    rank: 73,
    name: "MiniMax Hailuo 2.3",
    category: "Production",
    helps: "Text and image-to-video with precise camera and physics control, expressive micro-movements, and a Media Agent for multi-step generation workflows",
    price: "Free tier available; Hailuo 2.3 Fast ~50% lower than Standard; API on Pro Max+",
    budgetFit: "indie",
    link: "hailuoai.video",
    roles: ["Director","DOP (Director of Photography)","Editor"],
    shortDescription: "Cost-effective cinematic generator when prompts must obey camera moves — not random motion",
    howToUse: [
      "Step 1: Create an account at hailuoai.video or minimax.io",
      "Step 2: Choose Text-to-Video or Image-to-Video mode",
      "Step 3: Write explicit camera moves — dolly, rack focus, handheld, pan",
      "Step 4: Use Hailuo 2.3 Fast for iterations and Standard for hero shots",
      "Step 5: Download clips for edit assemblies or pre-vis boards",
    ],
    examplePrompt: "Handheld chase in narrow alley, overcast, wet pavement reflections, whip pan to close-up, shallow DOF, no text overlays",
  },
  {
    rank: 74,
    name: "Artlist Studio",
    category: "Production",
    helps: "Shot-by-shot AI production with character and location tags, cross-scene consistency, cinematic framing, and frame-to-shot extension — paired with the Artlist AI Toolkit model hub",
    price: "Included on Artlist AI plans (Starter+); credits shared across Toolkit and Studio",
    budgetFit: "both",
    link: "artlist.io/studio",
    roles: ["Director","Producer / Line Producer","Production Designer","DOP (Director of Photography)"],
    shortDescription: "Direct AI like a real shoot: cast, scout, frame, and extend sequences with visual continuity",
    howToUse: [
      "Step 1: Open artlist.io/studio on an Artlist AI plan",
      "Step 2: Define prompt tags for recurring characters and locations",
      "Step 3: Frame shots with angle and composition controls",
      "Step 4: Generate clips and extend from key frames into new shots",
      "Step 5: Export sequences for hybrid live-action planning or pre-vis",
    ],
    examplePrompt: "Three-shot dialogue scene: same tagged protagonist in neon diner — OTS, close-up, wide — maintain wardrobe and lighting",
  },
  {
    rank: 75,
    name: "Frame.io",
    category: "Post-Prod",
    helps: "Cloud review with frame-accurate comments, version stacks, Camera to Cloud dailies, semantic search, and Adobe Premiere integration",
    price: "Free (2 users, 2GB); Pro from ~$15/user/mo; Team from ~$25/user/mo",
    budgetFit: "both",
    link: "frame.io",
    catalogKind: "software" as const,
    roles: ["Editor","Director","Producer / Line Producer","1st Assistant Director"],
    shortDescription: "Industry-standard cut review — timecoded notes, version compare, and dailies without email chaos",
    howToUse: [
      "Step 1: Create a project on frame.io and upload your assembly or graded cut",
      "Step 2: Share a review link with comment permissions for director and producer",
      "Step 3: Stack versions and use the comparison viewer for picture changes",
      "Step 4: Search transcripts and visuals with natural-language find (V4)",
      "Step 5: Push approved notes back to Premiere via the Frame.io extension",
    ],
    examplePrompt: "Share Assembly Cut v3 with director and producer — picture-only comments, passphrase on festival screener link",
  },
  {
    rank: 76,
    name: "ShotDeck",
    category: "Pre-Prod",
    helps: "Searchable HD movie-stills library tagged by lighting, lens, composition, color, mood, and era — build shareable look decks for crew alignment",
    price: "from $99.95/yr (~$8.33/mo) or $12.95/mo; 2-week free trial",
    budgetFit: "both",
    link: "shotdeck.com",
    roles: ["DOP (Director of Photography)","Director","Production Designer","Gaffer (Lighting)","Costume Designer"],
    shortDescription: "Find the exact cinematic frame for your look — millions of tagged stills built by filmmakers",
    howToUse: [
      "Step 1: Start a trial at shotdeck.com",
      "Step 2: Search by visual attributes — backlit, overcast, anamorphic, melancholic",
      "Step 3: Save shots to a deck per scene or character",
      "Step 4: Share deck links with production design and gaffer",
      "Step 5: Use color picker and similar-shots for grade and wardrobe references",
    ],
    examplePrompt: "Deck for Act 2 interrogation: single hard key, venetian blind shadows, cool cyan fill, 2.39:1, 1970s thriller palette",
  },
  {
    rank: 77,
    name: "Arc Studio Pro",
    category: "Pre-Prod",
    helps: "Industry-standard screenplay formatting, cloud sync, outlining, revision history, and real-time writer collaboration with Fountain and Final Draft export",
    price: "Free (2 scripts, watermarked PDF); Essentials $69/yr; Pro $99 first year then ~$79/yr",
    budgetFit: "indie",
    link: "arcstudiopro.com",
    catalogKind: "software" as const,
    roles: ["Director","Producer / Line Producer","Script Supervisor"],
    shortDescription: "Write and iterate scripts fast — export clean FDX for breakdown and scheduling tools",
    howToUse: [
      "Step 1: Sign up free at arcstudiopro.com",
      "Step 2: Outline beats then draft in script mode",
      "Step 3: Invite co-writer or script supervisor for comments",
      "Step 4: Track revisions across production draft colors",
      "Step 5: Export FDX to Filmustage, Studiovity, or Studiobinder",
    ],
    examplePrompt: "Tighten Act 1 from 18 to 14 pages — keep inciting incident on page 12, preserve final image beat",
  },
  {
    rank: 78,
    name: "Sync Labs",
    category: "Post-Prod",
    helps: "AI lip-sync and dubbing on real footage — sync replacement dialogue to on-camera performance including difficult angles and facial detail (sync-3, lipsync-2-pro)",
    price: "from ~$5/mo + usage (~$0.04–$0.13/sec depending on model)",
    budgetFit: "both",
    link: "sync.so",
    roles: ["Editor","Sound Designer","Producer / Line Producer"],
    shortDescription: "Fix ADR and localization without reshoots when talent cannot return to set",
    howToUse: [
      "Step 1: Create a project at sync.so",
      "Step 2: Upload picture lock or performance plate",
      "Step 3: Upload replacement dialogue or dubbed audio track",
      "Step 4: Choose lipsync-2-pro or sync-3 based on angle and beard complexity",
      "Step 5: Export synced clip for your NLE or sound mix",
    ],
    examplePrompt: "Replace corrupted dialogue on CU take 4B with clean ADR from booth session — match lip sync at 24fps",
  },
  {
    rank: 79,
    name: "AudioShake",
    category: "Post-Prod",
    helps: "AI stem separation — isolate dialogue, music, SFX, and instruments from mixed location or archival audio for cleanup, ADR prep, and clearance documentation",
    price: "Indie from ~$20/mo (4 stems); API credit-based (~1.5 credits/min for dialogue/SFX models)",
    budgetFit: "both",
    link: "audioshake.ai",
    roles: ["Sound Designer","Editor","Lawyer / Clearance"],
    shortDescription: "Unmix messy production audio when you cannot get another take on location",
    howToUse: [
      "Step 1: Upload mixed WAV or production audio at audioshake.ai",
      "Step 2: Select dialogue, effects, and music_fx separation targets",
      "Step 3: Download stems for DAW rebalance or cleaner dialogue chain",
      "Step 4: Feed cleaner dialogue into Descript or your ADR workflow",
      "Step 5: Document separated stems for music clearance if needed",
    ],
    examplePrompt: "Split café scene boom mix — isolate dialogue from espresso machine bed and distant music for ADR session",
  }
];

/**
 * Catalog kind for UI badges:
 * - `gear`: retailers (category "Gear")
 * - `ai`: default — most catalog entries are AI-first or AI-heavy editors, generators, libraries, and hybrid apps
 * - `software`: optional override (`catalogKind: "software"`) for rare, primarily traditional listings only
 */
export function getCatalogKind(tool: Tool): CatalogKind {
  if (tool.catalogKind) return tool.catalogKind;
  if (tool.category === "Gear") return "gear";
  return "ai";
}

/** Stable join key between `allTools` and workflow / budget presets (unique per tool). */
export function getToolByRank(rank: number): Tool | undefined {
  return allTools.find((t) => t.rank === rank);
}

/** True when a tracked partner / affiliate URL is configured (accepted partnership). */
export function hasPartnerLink(tool: Tool): boolean {
  return Boolean(tool.affiliateLink?.trim());
}

/**
 * Role spotlight: prefer accepted Partner tools (lowest rank among partners), else top catalog rank.
 * Aligns SPOTLIGHT with affiliate partners without overriding roles that have no partner fit.
 */
export function getSpotlightToolForRole(role: string): Tool | null {
  const matches = allTools.filter((t) => t.roles.includes(role));
  if (matches.length === 0) return null;

  const partners = matches.filter(hasPartnerLink).sort((a, b) => a.rank - b.rank);
  if (partners.length > 0) return partners[0];

  return matches.sort((a, b) => a.rank - b.rank)[0];
}

/** Default line items for Budget Templates — derived from catalog so renames/prices stay in sync. */
export const BUDGET_DEFAULT_MICRO_ROWS = [
  { rank: 6, qty: 1 },
  { rank: 8, qty: 1 },
  { rank: 5, qty: 1 },
  { rank: 7, qty: 1 },
  { rank: 3, qty: 1 },
  { rank: 10, qty: 1 },
  { rank: 11, qty: 1 },
  { rank: 4, qty: 1 },
] as const;

export const BUDGET_DEFAULT_LOW_ROWS = [
  { rank: 1, qty: 1 },
  { rank: 2, qty: 1 },
  { rank: 5, qty: 1 },
  { rank: 6, qty: 1 },
  { rank: 8, qty: 1 },
  { rank: 3, qty: 2 },
  { rank: 13, qty: 1 },
  { rank: 14, qty: 1 },
  { rank: 9, qty: 1 },
  { rank: 10, qty: 1 },
] as const;

function parseMonthlyFromPrice(price: string): number {
  const m = price.match(/\d+/);
  return m ? parseFloat(m[0]) : 15;
}

/** Row shape used by Budget Templates state in `page.tsx` (includes `catalogRank` for kit-style sync). */
export function budgetLineFromCatalogTool(tool: Tool, qty: number) {
  return {
    ...tool,
    catalogRank: tool.rank,
    qty,
    monthly: parseMonthlyFromPrice(tool.price),
  };
}

export function budgetLinesFromPreset(
  rows: readonly { readonly rank: number; readonly qty: number }[]
) {
  const out: ReturnType<typeof budgetLineFromCatalogTool>[] = [];
  for (const { rank, qty } of rows) {
    const t = getToolByRank(rank);
    if (!t) continue;
    out.push(budgetLineFromCatalogTool(t, qty));
  }
  return out;
}

export const workflowStages = [
  {
    title: "Pre-Production",
    description: "4–12 weeks: Turn your idea into a shoot-ready plan",
    steps: [
      {
        step: "1.1 Idea Development & Scripting",
        description: "Refine concept, write/rewrite script, create treatment.",
        tools: [11, 12, 4],
        proTip:
          "Draft in ChatGPT or Claude with clear INT./EXT. headings, then move locked scenes into LTX or Filmustage.",
      },
      {
        step: "1.2 Storyboarding & Visualization",
        description: "Create visual references and shot lists.",
        tools: [6, 8, 18],
        proTip:
          "Build still plates in Midjourney or Flux first — 2026 video tools work best from locked images, not only text.",
      },
      {
        step: "1.3 Casting & Talent",
        description: "Breakdown roles, hold auditions, negotiate contracts.",
        tools: [6, 8],
        proTip:
          "Generate character references before casting calls so actors can see the intended look.",
      },
      {
        step: "1.4 Location Scouting & Permits",
        description: "Find, photograph, and secure locations + permits.",
        tools: [26],
        proTip: "Always scout at the same time of day you plan to shoot. Lighting changes everything.",
      },
      {
        step: "1.5 Production Design, Props & Costume",
        description: "Design sets, source props, plan wardrobe.",
        tools: [6, 8, 28],
        proTip:
          "Use Midjourney/Flux for world plates; keep Style2D for costume explorations only.",
      },
      {
        step: "1.6 Makeup & Hair Planning",
        description: "Design looks, test products, create continuity references.",
        tools: [6, 18],
        proTip:
          "Photograph every approved look under shoot lighting. Continuity fixes in post are expensive.",
      },
      {
        step: "1.7 Budgeting, Scheduling & Crew",
        description: "Build detailed budget, shooting schedule, and assemble crew.",
        tools: [14, 11, 12],
        proTip:
          "After Sora shut down, budget for Kling / Veo / Runway / Seedance (often via CapCut) — not a single video vendor.",
      },
    ],
  },
  {
    title: "Production",
    description: "Principal photography: Capture the footage efficiently",
    steps: [
      {
        step: "2.1 Shooting & Cinematic Look",
        description: "Capture or generate cinematic coverage.",
        tools: [1, 2, 5],
        proTip:
          "Pick the model for the job: Runway for control, Veo for cinematic audio scenes, Kling for volume and motion.",
      },
      {
        step: "2.2 On-set Creative Support",
        description: "Generate quick VFX previews and reference clips.",
        tools: [5, 7, 15],
        proTip:
          "Image-to-video from your still board beats pure text prompts for consistency on set.",
      },
      {
        step: "2.3 Lighting, Grip & Camera",
        description: "Execute lighting design and camera movement.",
        tools: [21, 1],
        proTip:
          "Use Higgsfield when you need camera-profile language; use Runway when you need motion control.",
      },
      {
        step: "2.4 Sound Recording",
        description: "Capture clean production audio.",
        tools: [3],
        proTip:
          "Always record room tone. Pair production audio with ElevenLabs only for ADR / missing lines.",
      },
      {
        step: "2.5 Makeup, Costume & Continuity",
        description: "Daily application and matching shots.",
        tools: [6, 28],
        proTip: "Snap continuity photos at call time every day before rolling.",
      },
    ],
  },
  {
    title: "Post-Production",
    description: "4–12 weeks: Shape raw footage into the final film",
    steps: [
      {
        step: "3.1 Editing & Assembly",
        description: "Rough cut → Director’s cut.",
        tools: [10, 13, 3],
        proTip:
          "Many indie teams now assemble Kling/Seedance/Veo clips in CapCut, then finish grade in DaVinci.",
      },
      {
        step: "3.2 Visual Effects & Enhancement",
        description: "Add VFX, clean plates, upscale.",
        tools: [1, 9, 5],
        proTip: "Upscale late. Fix story and motion first — Topaz last.",
      },
      {
        step: "3.3 Sound Design & Dubbing",
        description: "Foley, ADR, voiceovers, multi-language dubbing.",
        tools: [3],
        proTip: "Record ADR while emotion is fresh; clone only when you must.",
      },
      {
        step: "3.4 Color Grading",
        description: "Final look and mood.",
        tools: [13, 21],
        proTip: "Grade in scene groups (day / night / interior) for consistency over perfection.",
      },
    ],
  },
  {
    title: "Distribution & Marketing",
    description: "Get your film seen and monetized",
    steps: [
      {
        step: "4.1 Marketing Assets",
        description: "Trailers, posters, social clips, behind-the-scenes.",
        tools: [10, 19, 6],
        proTip:
          "Ideogram for readable title cards; CapCut for trailer cutdowns from your AI + live plates.",
      },
      {
        step: "4.2 Localization & Dubbing",
        description: "Dub into other languages for global reach.",
        tools: [3],
        proTip: "Start with Spanish and Mandarin for festivals and streaming reach.",
      },
      {
        step: "4.3 Audience Targeting & Release",
        description: "Festival strategy, platform optimization, metadata.",
        tools: [11, 10],
        proTip: "Draft platform metadata in ChatGPT; cut vertical teasers in CapCut from the same master.",
      },
    ],
  },
];

for (const stage of workflowStages) {
  for (const step of stage.steps) {
    for (const rank of step.tools) {
      if (!getToolByRank(rank)) {
        console.warn(
          `[data] workflow step "${step.step}" references unknown catalog rank ${rank}`
        );
      }
    }
  }
}

/** Merge saved My Kit JSON with the current catalog (by `catalogRank`, then by `name`). */
export function rehydrateKitEntry(entry: unknown): unknown {
  if (!entry || typeof entry !== "object") return entry;
  const e = entry as Record<string, unknown>;
  const rank =
    typeof e.catalogRank === "number" && Number.isFinite(e.catalogRank)
      ? e.catalogRank
      : undefined;
  const name = typeof e.name === "string" ? e.name : "";
  const t =
    rank != null ? getToolByRank(rank) : allTools.find((x) => x.name === name);
  if (!t) return entry;
  const qty =
    typeof e.qty === "number" && Number.isFinite(e.qty) && e.qty > 0
      ? Math.floor(e.qty)
      : 1;
  return {
    ...t,
    catalogRank: t.rank,
    qty,
    monthly: parseMonthlyFromPrice(t.price),
  };
}

export const SITE_CONTACT_EMAIL = "otherprojectsx@gmail.com" as const;

/** Linked from Budget Templates — must be shared so “Anyone with the link” can view for export URLs to work without sign-in. */
export const BUDGET_TEMPLATE_SHEETS = {
  micro: {
    id: "1xO5LM1eHio8rS8O1SGf4WF1EXYc7YhJO5QnPSjLXxWQ",
    editUrl:
      "https://docs.google.com/spreadsheets/d/1xO5LM1eHio8rS8O1SGf4WF1EXYc7YhJO5QnPSjLXxWQ/edit?usp=sharing",
  },
  low: {
    id: "1L9iFnldMosGjrNRwOzhVN8nYhUwg5BL7zDngWKpRpQs",
    editUrl:
      "https://docs.google.com/spreadsheets/d/1L9iFnldMosGjrNRwOzhVN8nYhUwg5BL7zDngWKpRpQs/edit?usp=sharing",
  },
} as const;

/** Direct download (new tab). Works on mobile when the spreadsheet is publicly viewable. */
export function googleSpreadsheetExportUrl(
  spreadsheetId: string,
  format: "xlsx" | "pdf" = "xlsx"
): string {
  return `https://docs.google.com/spreadsheets/d/${spreadsheetId}/export?format=${format}`;
}
